name: Send Daily Thoughts
on:
  schedule:
    - cron: '0 2 * * *'   # 4 AM Malawi
    - cron: '0 18 * * *'  # 8 PM Malawi
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python daily_thought_sender.py

